# use https because github.io demands it
baseurl = "http://darakshan.com/"
publishdir = ".."
languageCode = "en-us"
title = "Darakshan's Direction"
# theme = "blackburn"
theme = "hugo_theme_robust_hacked"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[taxonomies]
#   tag = "tags"
#   topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Essays and Travels"
  brand = "Darakshan"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "01/02/06 03:04pm"
  toc = 0
  Author = "Darakshan"
  

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Essays"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "essays"
    url = "/essays/"
  [[menu.main]]
    name = "Travel"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "travel"
    url = "/travel/"
  [[menu.main]]
    name = "Floetry"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 4
    identifier = "floetry"
    url = "/floetry/"
  [[menu.main]]
    name = "About Me"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
